### ISSUE TITLE
NDesk.Options

### ISSUE THREAD

**Issue by JustinBritt** [OPTANO/optano.algorithm.tuner#1]
The version of NDesk.Options that this references does not have .NET Standard targets. Is it possible to replace it with one that does (e.g., https://www.nuget.org/packages/NDesk.Options.Patched/)?

**Comment by jpkempkes** [comment]
We are currently working on version 1 and will take this into account

**Comment by jannicklange** [comment]
The NDesk.Options.Patched package seems to have an issue when an Option.Descrption ends with a line break. <br/>
Once our [PR/Fix](https://github.com/nano-byte/NDesk.Options/issues/2) gets accepted + released, we'll migrate to the patched package.
